import { TheHeader } from '@/components/TheHeader'
import './globals.css'
import { Inter } from 'next/font/google'
import { TheFooter } from '@/components/TheFooter'
import { Metadata } from 'next'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'First Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TheHeader />
        <main className='main-container'>
          {children}
        </main>
        <TheFooter />
      </body>
    </html>
  )
}
